import Head from "next/head";
import { Fotter } from "../components/Footer/Footer";
import { Main } from "../components/Main/Main";
import { Header } from "../components/Header/Header";
import { useCallback, useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  /*  const foo = 1;
  const handleClick = useCallback((e) => {
    console.log(e.target.href);
    e.preventDefault();
    alert(foo);
  }, []); */
  /* useCallbackを使うとページの再レンダリングの時の再生成を防ぐことができる */
  /* この処理はHomeの外に記述してもよい */
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <a href="/about"/*  onClick={handleClick} */>
        ボタン
      </a>
      <Main page="index" />

      <Fotter />
    </div>
  );
}

/* 処理とコンポーネントは分ける */
/* メソッドを中に書くとページの再レンダリングの時に中で書いていると再レンダリングされてしま */

/* アクションの種類
１ユーザーアクションのイベント
２タイミングで起こしたいイベント　オフラインオンライン */

/*  コンポーネントのライフサイクル*/
