import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Fotter } from '../components/Fotter'
import { Links } from '../components/Links'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">About Page!!</a>
        </h1>

        <p className={styles.description}>
          こんにちは started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Links/>
      </main>

     <Fotter/>
    </div>
  )
}
